CREATE TABLE USER$BANASPIH.PUBLIC.CLICK_STREAMING (
    CLICK_STREAMING_ID VARCHAR PRIMARY KEY,
    EVENT_TYPE VARCHAR NOT NULL,
    USER_ID VARCHAR NOT NULL,
    SESSION_ID VARCHAR NOT NULL,
    CLICK_STREAM_TIMESTAMP TIMESTAMP,
    URL VARCHAR NOT NULL,
    PAGE VARCHAR NOT NULL,
    DWELL_SECONDS INT NOT NULL,
    SCROLL_DEPTH_PCT INT NOT NULL,
    USER_AGENT  VARCHAR NOT NULL,
    REFERER VARCHAR NOT NULL,
    IP VARCHAR NOT NULL

)